name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
            ./addingADOtoGithub.ps1 -GitHubDestinationPAT ${{ secrets.SYNC_GITHUB }} -ADOSourcePAT ${{ secrets.SYNC_GITHUB_AZUREDEVOPS }}
